# Generated by Django 4.1.5 on 2023-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="Дата создания"),
        ),
    ]
