# Generated by Django 4.1.5 on 2023-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="created_at",),
    ]
